Missing include in src/ui/calibration/main.cc
libmv/src/ui/calibration/main.cc: In member function ‘void MainWindow::process()’:
libmv/src/ui/calibration/main.cc:389:41: error: ‘CV_TERMCRIT_EPS’ was not declared in this scope
libmv/src/ui/calibration/main.cc:389:59: error: ‘CV_TERMCRIT_ITER’ was not declared in this scope